---
# Sheet names to include
Sheet: "*Data*"

# List of column names to include
Column Names:
  - A
  - B
  - C
  - D
  - E
  - F
  - G
  - H
  - I
  - J
  - K

# List of cells to extract
Cells:
  - F1
  - H1
  - D1
  - H3
  - D3
  - E2
  - F3
  - B3
  - B2
  - G2
  - B1
